### ISSUE TITLE
Issue with loading ndpi image >6GB 

### ISSUE THREAD

**Issue by amrit200192** [openslide/openslide-bin#244] opened 2024-04-12 08:57 UTC
Hi Team ,
I am trying to load ndpi image which size is greater than 6 GB.
And i am getting error like below.
C:\workspace\2023-08-25-027_01\2023-08-25-027_01.ndpi
127.0.0.1 - - [12/Apr/2024 14:18:48] "←[33mGET /2023-08-25-027_01%5C2023-08-25-027_01.ndpi HTTP/1.1←[0m" 404 -
C:\workspace\2023-08-25-027_01\2023-08-25-027_01.ndpi
127.0.0.1 - - [12/Apr/2024 14:19:13] "←[33mGET /2023-08-25-027_01%5C2023-08-25-027_01.ndpi HTTP/1.1←[0m" 404 -

**Comment by bgilbert** [comment] 2024-04-17 03:50
Duplicate of https://github.com/openslide/openslide/issues/174.

**Closed by bgilbert** 2024-04-17 03:50 UTC
